### ISSUE TITLE
Setting a parameter can create a mismatch in parameter value between the internal value and the ros2 param value

### ISSUE THREAD

**Issue by JasperTan97** [aica-technology/modulo#100]
When setting a parameter, the `on_validate_parameter_callback` is called, and sometimes the value of the parameter is changed (for example, if the candidate value is out of range) instead of rejected. However, if we set the parameter via the ROS2 cli, ROS2 does not allow a parameter to be set or changed during the set parameter callback, which includes `on_validate_parameter_callback`. Hence, the internal value of our parameter may get updated via the logic in `on_validate_parameter_callback`, but the value of the ROS2 parameter is left as what has been set. 

From testing, both using the ros2 param cli and the AICA API (via localhost:5000) have the same issue. There needs to be a solution to re-synchronise both parameter maps.

**Comment by JasperTan97** [comment]
@domire8

**Comment by domire8** [comment]
Yeah this is an interesting one @eeberhard. It is indeed a problem that you can modify the value of the shared parameter object that one gets `on_validate_parameter_callback` which as a consequence will have an effect on the value of the internal parameter object value, but NOT on the value of the parameter on the ROS 2 server.

"Re-synchronize" the parameters is one way, even though I wouldn't see an efficient way to do that right now. A more correct way would maybe be to prohibit a change to the shared parameter object `on_validate_parameter_callback`.

**Comment by eeberhard** [comment]
Interesting. Let me just summarize again the intended behavior of the parameter validation callback:

During parameter validation, we have a kind of "parameter candidate" which comes from the ROS 2 interface which is passed to `on_validate_parameter_callback`. This function is allowed to modify the parameter candidate and "lock it in" by returning `true`, else discard the candidate by returning `false`. The intention here was to automatically allow numeric parameters to be constrained by limits, string parameters to be sanitized, etc for a smoother user experience.

Now to check that I understand the issue correctly; what I expect is that modifying the parameter candidate in the callback _does_ modify the actual ROS 2 parameter as expected when setting a parameter through a parameter client from another node (for example the Dynamic State Engine in the AICA application framework). You are saying it does _not_ modify the actual ROS 2 parameter when setting a parameter through the ROS 2 CLI.

> However, if we set the parameter via the ROS2 cli, ROS2 does not allow a parameter to be set or changed during the set parameter callback

I don't fully understand this; how can ROS 2 CLI set any parameter in that case? Do you just mean it can't be _changed_ (read-only)?

> A more correct way would maybe be to prohibit a change to the shared parameter object

Are you implying to remove the ability to modify parameter candidates entirely? For me that's a last resort, since I think this feature is otherwise a useful and powerful part of our abstraction.

I think it would be better to first understand why there is a difference between setting parameters through the CLI vs through other parameter clients (if there even is a difference at all; perhaps this problem has been present no matter where the parameter change originates from).

**Comment by domire8** [comment]
Looking at the node parameters interface we can see that there are three possible callbacks on set of a parameter:
```
struct PreSetParametersCallbackHandle
{
  RCLCPP_SMART_PTR_DEFINITIONS(PreSetParametersCallbackHandle)

  using PreSetParametersCallbackType =
    std::function<void (std::vector<rclcpp::Parameter> &)>;

  PreSetParametersCallbackType callback;
};

struct OnSetParametersCallbackHandle
{
  RCLCPP_SMART_PTR_DEFINITIONS(OnSetParametersCallbackHandle)

  using OnSetParametersCallbackType =
    std::function<
    rcl_interfaces::msg::SetParametersResult(
      const std::vector<rclcpp::Parameter> &)>;
  using OnParametersSetCallbackType [[deprecated("use OnSetParametersCallbackType instead")]] =
    OnSetParametersCallbackType;

  OnSetParametersCallbackType callback;
};

struct PostSetParametersCallbackHandle
{
  RCLCPP_SMART_PTR_DEFINITIONS(PostSetParametersCallbackHandle)

  using PostSetParametersCallbackType =
    std::function<void (const std::vector<rclcpp::Parameter> &)>;

  PostSetParametersCallbackType callback;
};
```
We're using the `OnSetParametersCallbackType` now, that has `const std::vector<rclcpp::Parameter> &` as argument. We see that the `PreSetParametersCallbackType` has a mutable argument `std::vector<rclcpp::Parameter> &`. However, there is no return value, so we couldn't reject parameters just by using this callback. I was somehow hoping the `PostSetParametersCallbackType` could be an easy fix but its also `const` so I'm back to square 1

**Comment by eeberhard** [comment]
> However, there is no return value, so we couldn't reject parameters just by using this callback

Couldn't we use our internal store of the parameter to overwrite the candidate parameter with the "old" value to functionally reject the change?
