### ISSUE TITLE
Publish predicates only on value change

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#122]
Currently, predicates are published at a fixed rate (component rate, or hardcoded rate for controllers) as well as on `set_predicate()`. It would be much more efficient to only publish predicates on change.

I present here three options in order of preference (last one is the highest one):
1. Drop the option of providing a functor as a predicate and just store the current predicate value in one single map. This would require derived components to always use `set_predicate` in order to set a predicate value. The advantage of this option is that only one map is required. The disadvantage is that we would remove a neat feature that is being used in multiple components.
2. Naive approach: simply add a second map that holds the previous predicate value and only publish if the new value is different from the old one.
3. Naive approach, in better: add a second map that holds the previous predicate value and only publish if the new value is different from the old one. Additionally, wrap all predicates in a functor, e.g. drop the `PredicateVariant` in order to make the `get_predicate` function slightly faster.

@bpapaspyros @eeberhard

**Comment by eeberhard** [comment]
Sorry for the late reply but I agree that keeping the API feature to provide a bool or function callback as a predicate is a good thing. For that reason we of course need to store the previous value to detect change. I also agree with point 3 that we can also store bool predicates as an anonymous function.

The only thing I don't particularly agree with is keeping two maps for predicate function and previous value, since then we need to keep the two in sync for each predicate. You might instead want to declare a simple predicate struct or class that holds both the function and the previously value, then build a map of that. You might then be able to add some simple methods to that class to query the current predicate value, check the previous value and update the previous value all from one external invocation.
